### ISSUE TITLE
Web UI FR:  Be able to view/generate full report

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1280] opened 2023-06-06 21:45 UTC
It would be nice to be able to generate the report from the Web UI to be able to easily view the high level findings (currently you need to click through each task to see if it had any relevant results).

**Comment by jleaniz** [comment] 2023-10-10 14:06
@aarontp seems like a duplicate of #1342

**Comment by aarontp** [comment] 2023-10-10 17:54
@jleaniz this one is slightly different, and I added a comment to the other one to help clarify.  This FR is to show the entire report in one view, and the other one is to show the report data for a given task at the task level/view.

**Closed** 2024-08-01 16:04 UTC
Labels: enhancement, webui
