### ISSUE TITLE
Turbinia not compatible with google-cloud-pubsub==0.29.0

### ISSUE THREAD

**Issue by berggren** [google/turbinia#96] opened 2017-11-08 22:58 UTC
pubsub.Client is now PublisherClient and SubscriberClient

**Comment by aarontp** [comment] 2017-11-22 19:18
Took a bit of digging to figure out exactly what is going on, but here is the redesign:
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3859

The underlying code still supports it, but it sounds like they're trying to push everyone to asynchronous based polling.  In the short term I'm just going to use the underlying .pull() method, and we can convert later if this thread indicates that it might not be supported in the long term.
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4338

**Comment by berggren** [comment] 2017-11-22 19:34
SGTM

**Comment by aarontp** [comment] 2017-11-23 00:23
Ok, so a few things:

I tried to just use the underlying implementation for .pull() by using the SubscriberClient directly from the gapic client in google.cloud.pubsub_v1.gapic.subscriber_client, but I couldn't get it to work correctly (it kept indefinitely hanging when waiting for messages rather than respecting the return_immediately flag).  I ended up just using the asynchronous interface and just sticking things on a queue for processing as needed.

I have initial support for asynchronous pulls with the latest library version in the pubsub-fix branch here:
https://github.com/google/turbinia/commit/cd0cd14cd32bf6089c427b6295e5af29aab4f28a

Only problem is that it looks like PSQ doesn't actually support it yet either, :(.  I filed this issue, but we might need to add that support ourselves:
https://github.com/GoogleCloudPlatform/psq/issues/32

**Comment by aarontp** [comment] 2017-12-07 21:03
We should be good to move forward to upgrading this.  PSQ has updated to use the latest version as of psq==0.6.0.  Hopefully no major refactors in the PSQ interface to go along with it, :)

**Comment by berggren** [comment] 2017-12-07 22:12
Woop Woop!

**Comment by aarontp** [comment] 2018-03-06 03:14
Note to self:  Unpin google-cloud-storage when this is fixed as well.

**Comment by beamcodeup** [comment] 2018-04-09 19:03
@aarontp FYI

Per https://github.com/grpc/grpc/issues/14892, gRPC doesn't support fork. Currently, we pin psq=0.5.0. The problem is this version fork() when psq.MultiprocessWorker(queue=...) is invoked and then segfaults.

I think we should explore upgrading psq to the latest version.

**Comment by aarontp** [comment] 2018-04-09 21:32
@beamcodeup: Ok, thanks.  It looks PSQ dropped the MultiprocessWorker
altogether in GoogleCloudPlatform/psq/pull/34, so specifying -S to the
worker should be equivalent in this particular case.  We do need to upgrade
anyway though.  I have a PR that is drafted, but completely untested, so
I'll up the priority of finishing that.

**Comment by aarontp** [comment] 2018-07-09 21:35
Fixed in #198

**Closed by aarontp** 2018-07-09 21:35 UTC
Labels: Prio1, enhancement
