### ISSUE TITLE
Fix API server tests

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1308] opened 2023-07-19 01:17 UTC
There are a couple tests currently failing:
```

======================================================================
FAIL: testRequestStatus (api.api_server_test.testTurbiniaAPIServer)
Test getting Turbinia Request status.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/tmp/turbinia/api/api_server_test.py", line 174, in testRequestStatus
    self.assertEqual(expected_result_dict, result)
AssertionError: OrderedDict([('evidence_name', '/evidence[1377 chars]}])]) != {'detail': 'Error retrieving request information'}

======================================================================
FAIL: testRequestSummary (api.api_server_test.testTurbiniaAPIServer)
Test getting Turbinia Request status summary.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/tmp/turbinia/api/api_server_test.py", line 195, in testRequestSummary
    self.assertEqual(expected_result, result)
AssertionError: {'requests_status': [{'evidence_name': '/ev[292 chars][]}]} != {'detail': 'Error retrieving requests summary'}
Diff is 657 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

**Comment by jleaniz** [comment] 2023-07-21 19:12
Closing as duplicate of #1304

**Closed by jleaniz** 2023-07-21 19:12 UTC
Labels: bug
