### ISSUE TITLE
Web UI FR: Sort Tasks

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1281] opened 2023-06-06 21:47 UTC
The Task results have a "priority" that could potentially be used to filter/sort results.  It would be nice to expose this via the UI to 1) see what tasks have interesting findings and 2) be able to sort the tasks based on this.

**Comment by aarontp** [comment] 2023-06-06 21:50
Changing this to be a little more generic since I don't see a way to sort tasks more generally.

It would also be nice to be able to sort tasks by task name.

**Comment by jleaniz** [comment] 2023-10-10 14:05
@aarontp seems like a duplicate of #1341

**Comment by aarontp** [comment] 2023-10-10 18:03
Yeah, thanks, this is a dupe.

**Closed** 2023-10-10 18:03 UTC
Labels: enhancement, webui
