### ISSUE TITLE
JupyterConfigFile extraction failes

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#852] opened 2021-07-23 12:26 UTC
JupyterAnalysis job fails as the fileextraction task fails.

```
sudo image_export.py --no-hashes --logfile /var/lib/turbinia/output/1627042076-e227d536fdbb4dac8bd064ce804c21c5-FileArtifactExtractionTask/e227d536fdbb4dac8bd064ce804c21c5.log -w /var/lib/turbinia/output/1627042076-e227d536fdbb4dac8bd064ce804c21c5-FileArtifactExtractionTask/export --partitions all --artifact_filters JupyterConfigFile /dev/loop0
```

```
2021-07-23 12:08:27,024 [WARNING] (MainProcess) PID:156658 <image_export> Unable to build collection filters with error: No valid file system find specifications were built from artifacts.
```

**Comment by aarontp** [comment] 2021-09-27 20:20
#901 is a dupe of this, but closing this one as 901 has a bit more log info.

**Closed by aarontp** 2021-09-27 20:20 UTC
